In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'  #默认为'last'

In [2]:
import pandas as pd
import numpy
from sklearn import tree
from sklearn import neighbors
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import train_test_split
from sklearn import svm

In [3]:
train_set = pd.read_csv("./train_set.csv")
train_set = pd.DataFrame(train_set)
train_set = train_set.drop(columns="ID")
# test_set = pd.DataFrame(train_set)
train_set.head()
# test_set.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,43,management,married,tertiary,no,291,yes,no,unknown,9,may,150,2,-1,0,unknown,0
1,42,technician,divorced,primary,no,5076,yes,no,cellular,7,apr,99,1,251,2,other,0
2,47,admin.,married,secondary,no,104,yes,yes,cellular,14,jul,77,2,-1,0,unknown,0
3,28,management,single,secondary,no,-994,yes,yes,cellular,18,jul,174,2,-1,0,unknown,0
4,42,technician,divorced,secondary,no,2974,yes,no,unknown,21,may,187,5,-1,0,unknown,0

In [4]:
train_set.shape

(25317, 17)

In [5]:
vec = DictVectorizer(sparse=False)
train_set = vec.fit_transform(train_set.to_dict(orient="record"))
train_set = pd.DataFrame(train_set)
train_set.columns = vec.feature_names_
train_set

,age,balance,campaign,contact=cellular,contact=telephone,contact=unknown,day,default=no,default=yes,duration,...,month=nov,month=oct,month=sep,pdays,poutcome=failure,poutcome=other,poutcome=success,poutcome=unknown,previous,y
0,43.0,291.0,2.0,0.0,0.0,1.0,9.0,1.0,0.0,150.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,42.0,5076.0,1.0,1.0,0.0,0.0,7.0,1.0,0.0,99.0,...,0.0,0.0,0.0,251.0,0.0,1.0,0.0,0.0,2.0,0.0
2,47.0,104.0,2.0,1.0,0.0,0.0,14.0,1.0,0.0,77.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,28.0,-994.0,2.0,1.0,0.0,0.0,18.0,1.0,0.0,174.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,42.0,2974.0,5.0,0.0,0.0,1.0,21.0,1.0,0.0,187.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25312,55.0,8180.0,2.0,1.0,0.0,0.0,14.0,1.0,0.0,854.0,...,0.0,0.0,0.0,360.0,1.0,0.0,0.0,0.0,1.0,1.0
25313,52.0,961.0,1.0,1.0,0.0,0.0,18.0,1.0,0.0,222.0,...,0.0,0.0,0.0,553.0,1.0,0.0,0.0,0.0,4.0,1.0
25314,35.0,300.0,2.0,0.0,0.0,1.0,13.0,1.0,0.0,945.0,...,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,1.0
25315,37.0,66.0,2.0,1.0,0.0,0.0,18.0,1.0,0.0,1164.0,...,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,1.0
25316,52.0,40.0,3.0,1.0,0.0,0.0,19.0,1.0,0.0,1265.0,...,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,1.0

In [6]:
X = train_set.iloc[:,:-1]
Y = train_set.iloc[:,-1]

In [7]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=33)
x_train
# y_train.shape

,age,balance,campaign,contact=cellular,contact=telephone,contact=unknown,day,default=no,default=yes,duration,...,month=may,month=nov,month=oct,month=sep,pdays,poutcome=failure,poutcome=other,poutcome=success,poutcome=unknown,previous
5884,30.0,105.0,1.0,1.0,0.0,0.0,21.0,1.0,0.0,75.0,...,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0
16037,36.0,2176.0,2.0,0.0,0.0,1.0,28.0,1.0,0.0,52.0,...,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0
16348,43.0,0.0,3.0,1.0,0.0,0.0,7.0,1.0,0.0,240.0,...,1.0,0.0,0.0,0.0,293.0,1.0,0.0,0.0,0.0,5.0
20597,50.0,-465.0,11.0,0.0,0.0,1.0,30.0,1.0,0.0,42.0,...,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0
10583,32.0,393.0,2.0,1.0,0.0,0.0,28.0,1.0,0.0,458.0,...,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,48.0,2204.0,1.0,1.0,0.0,0.0,12.0,1.0,0.0,45.0,...,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0
578,49.0,766.0,4.0,1.0,0.0,0.0,7.0,1.0,0.0,150.0,...,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0
5848,34.0,10.0,1.0,1.0,0.0,0.0,22.0,1.0,0.0,81.0,...,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0
2439,36.0,1392.0,1.0,1.0,0.0,0.0,17.0,1.0,0.0,231.0,...,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0
23572,26.0,2509.0,3.0,1.0,0.0,0.0,27.0,1.0,0.0,776.0,...,1.0,0.0,0.0,0.0,97.0,0.0,0.0,1.0,0.0,3.0

In [ ]:
#传入的模型不一定要训练好的
model = svm.SVC(kernel='linear')
model.fit(x_train,y_train)
model.score(x_test,y_test)

In [ ]:
test_set = pd.read_csv("./test_set.csv")
ID = test_set['ID']
test_set = test_set.drop(columns="ID")
test_set

In [ ]:
vec = DictVectorizer(sparse=False)
data = vec.fit_transform(test_set.to_dict(orient="record"))
data = pd.DataFrame(data)
data.columns = vec.feature_names_
data

In [ ]:
predict = AB.predict_proba(data)
result = pd.DataFrame(predict).iloc[:,1]
ID = pd.DataFrame(ID)
ID.insert(1,"pred",result)
ID.to_csv("result.csv",index=False)